// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.trigon.qrcode.domain;

import com.trigon.qrcode.domain.QRCode;
import com.trigon.qrcode.domain.QRCodeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect QRCodeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QRCodeDataOnDemand: @Component;
    
    private Random QRCodeDataOnDemand.rnd = new SecureRandom();
    
    private List<QRCode> QRCodeDataOnDemand.data;
    
    public QRCode QRCodeDataOnDemand.getNewTransientQRCode(int index) {
        QRCode obj = new QRCode();
        return obj;
    }
    
    public QRCode QRCodeDataOnDemand.getSpecificQRCode(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        QRCode obj = data.get(index);
        Long id = obj.getId();
        return QRCode.findQRCode(id);
    }
    
    public QRCode QRCodeDataOnDemand.getRandomQRCode() {
        init();
        QRCode obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return QRCode.findQRCode(id);
    }
    
    public boolean QRCodeDataOnDemand.modifyQRCode(QRCode obj) {
        return false;
    }
    
    public void QRCodeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = QRCode.findQRCodeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'QRCode' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<QRCode>();
        for (int i = 0; i < 10; i++) {
            QRCode obj = getNewTransientQRCode(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
