// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.trigon.qrcode.domain;

import com.trigon.qrcode.domain.QRCode;
import com.trigon.qrcode.domain.QRCodeDataOnDemand;
import com.trigon.qrcode.domain.QRCodeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QRCodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QRCodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QRCodeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QRCodeIntegrationTest: @Transactional;
    
    @Autowired
    QRCodeDataOnDemand QRCodeIntegrationTest.dod;
    
    @Test
    public void QRCodeIntegrationTest.testCountQRCodes() {
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", dod.getRandomQRCode());
        long count = QRCode.countQRCodes();
        Assert.assertTrue("Counter for 'QRCode' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QRCodeIntegrationTest.testFindQRCode() {
        QRCode obj = dod.getRandomQRCode();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to provide an identifier", id);
        obj = QRCode.findQRCode(id);
        Assert.assertNotNull("Find method for 'QRCode' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QRCode' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QRCodeIntegrationTest.testFindAllQRCodes() {
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", dod.getRandomQRCode());
        long count = QRCode.countQRCodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'QRCode', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QRCode> result = QRCode.findAllQRCodes();
        Assert.assertNotNull("Find all method for 'QRCode' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QRCode' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QRCodeIntegrationTest.testFindQRCodeEntries() {
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", dod.getRandomQRCode());
        long count = QRCode.countQRCodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QRCode> result = QRCode.findQRCodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QRCode' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QRCode' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QRCodeIntegrationTest.testFlush() {
        QRCode obj = dod.getRandomQRCode();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to provide an identifier", id);
        obj = QRCode.findQRCode(id);
        Assert.assertNotNull("Find method for 'QRCode' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQRCode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QRCode' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QRCodeIntegrationTest.testMergeUpdate() {
        QRCode obj = dod.getRandomQRCode();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to provide an identifier", id);
        obj = QRCode.findQRCode(id);
        boolean modified =  dod.modifyQRCode(obj);
        Integer currentVersion = obj.getVersion();
        QRCode merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QRCode' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QRCodeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", dod.getRandomQRCode());
        QRCode obj = dod.getNewTransientQRCode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QRCode' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QRCode' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'QRCode' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QRCodeIntegrationTest.testRemove() {
        QRCode obj = dod.getRandomQRCode();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QRCode' failed to provide an identifier", id);
        obj = QRCode.findQRCode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QRCode' with identifier '" + id + "'", QRCode.findQRCode(id));
    }
    
}
