// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.trigon.qrcode.domain;

import com.trigon.qrcode.domain.QRCodeDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect QRCodeDataOnDemand_Roo_Configurable {
    
    declare @type: QRCodeDataOnDemand: @Configurable;
    
}
